/**
 * BillingManagementClient
 * Billing client provides access to billing resources for Azure subscriptions.
 *
 * The version of the OpenAPI document: 2020-05-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../../BaseApiClient";
import BillingRoleAssignment from '../model/BillingRoleAssignment';
import BillingRoleAssignmentListResult from '../model/BillingRoleAssignmentListResult';
import ErrorResponse from '../model/ErrorResponse';

/**
* BillingRoleAssignments service.
* @module api/BillingRoleAssignmentsApi
* @version 2020-05-01
*/
export default class BillingRoleAssignmentsApi {

    /**
    * Constructs a new BillingRoleAssignmentsApi. 
    * @alias module:api/BillingRoleAssignmentsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the billingRoleAssignmentsDeleteByBillingAccount operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsDeleteByBillingAccountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a role assignment for the caller on a billing account. The operation is supported for billing accounts with agreement type Microsoft Partner Agreement or Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {String} billingRoleAssignmentName The ID that uniquely identifies a role assignment.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsDeleteByBillingAccountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignment}
     */
    billingRoleAssignmentsDeleteByBillingAccount(apiVersion, billingAccountName, billingRoleAssignmentName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsDeleteByBillingAccount");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsDeleteByBillingAccount");
      }
      // verify the required parameter 'billingRoleAssignmentName' is set
      if (billingRoleAssignmentName === undefined || billingRoleAssignmentName === null) {
        throw new Error("Missing the required parameter 'billingRoleAssignmentName' when calling billingRoleAssignmentsDeleteByBillingAccount");
      }

      let pathParams = {
        'billingAccountName': billingAccountName,
        'billingRoleAssignmentName': billingRoleAssignmentName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignment;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingRoleAssignments/{billingRoleAssignmentName}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the billingRoleAssignmentsDeleteByBillingProfile operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsDeleteByBillingProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a role assignment for the caller on a billing profile. The operation is supported for billing accounts with agreement type Microsoft Partner Agreement or Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {String} billingProfileName The ID that uniquely identifies a billing profile.
     * @param {String} billingRoleAssignmentName The ID that uniquely identifies a role assignment.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsDeleteByBillingProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignment}
     */
    billingRoleAssignmentsDeleteByBillingProfile(apiVersion, billingAccountName, billingProfileName, billingRoleAssignmentName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsDeleteByBillingProfile");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsDeleteByBillingProfile");
      }
      // verify the required parameter 'billingProfileName' is set
      if (billingProfileName === undefined || billingProfileName === null) {
        throw new Error("Missing the required parameter 'billingProfileName' when calling billingRoleAssignmentsDeleteByBillingProfile");
      }
      // verify the required parameter 'billingRoleAssignmentName' is set
      if (billingRoleAssignmentName === undefined || billingRoleAssignmentName === null) {
        throw new Error("Missing the required parameter 'billingRoleAssignmentName' when calling billingRoleAssignmentsDeleteByBillingProfile");
      }

      let pathParams = {
        'billingAccountName': billingAccountName,
        'billingProfileName': billingProfileName,
        'billingRoleAssignmentName': billingRoleAssignmentName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignment;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/billingRoleAssignments/{billingRoleAssignmentName}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the billingRoleAssignmentsDeleteByInvoiceSection operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsDeleteByInvoiceSectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a role assignment for the caller on an invoice section. The operation is supported for billing accounts with agreement type Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {String} billingProfileName The ID that uniquely identifies a billing profile.
     * @param {String} invoiceSectionName The ID that uniquely identifies an invoice section.
     * @param {String} billingRoleAssignmentName The ID that uniquely identifies a role assignment.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsDeleteByInvoiceSectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignment}
     */
    billingRoleAssignmentsDeleteByInvoiceSection(apiVersion, billingAccountName, billingProfileName, invoiceSectionName, billingRoleAssignmentName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsDeleteByInvoiceSection");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsDeleteByInvoiceSection");
      }
      // verify the required parameter 'billingProfileName' is set
      if (billingProfileName === undefined || billingProfileName === null) {
        throw new Error("Missing the required parameter 'billingProfileName' when calling billingRoleAssignmentsDeleteByInvoiceSection");
      }
      // verify the required parameter 'invoiceSectionName' is set
      if (invoiceSectionName === undefined || invoiceSectionName === null) {
        throw new Error("Missing the required parameter 'invoiceSectionName' when calling billingRoleAssignmentsDeleteByInvoiceSection");
      }
      // verify the required parameter 'billingRoleAssignmentName' is set
      if (billingRoleAssignmentName === undefined || billingRoleAssignmentName === null) {
        throw new Error("Missing the required parameter 'billingRoleAssignmentName' when calling billingRoleAssignmentsDeleteByInvoiceSection");
      }

      let pathParams = {
        'billingAccountName': billingAccountName,
        'billingProfileName': billingProfileName,
        'invoiceSectionName': invoiceSectionName,
        'billingRoleAssignmentName': billingRoleAssignmentName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignment;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}/billingRoleAssignments/{billingRoleAssignmentName}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the billingRoleAssignmentsGetByBillingAccount operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsGetByBillingAccountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets a role assignment for the caller on a billing account. The operation is supported for billing accounts with agreement type Microsoft Partner Agreement or Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {String} billingRoleAssignmentName The ID that uniquely identifies a role assignment.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsGetByBillingAccountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignment}
     */
    billingRoleAssignmentsGetByBillingAccount(apiVersion, billingAccountName, billingRoleAssignmentName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsGetByBillingAccount");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsGetByBillingAccount");
      }
      // verify the required parameter 'billingRoleAssignmentName' is set
      if (billingRoleAssignmentName === undefined || billingRoleAssignmentName === null) {
        throw new Error("Missing the required parameter 'billingRoleAssignmentName' when calling billingRoleAssignmentsGetByBillingAccount");
      }

      let pathParams = {
        'billingAccountName': billingAccountName,
        'billingRoleAssignmentName': billingRoleAssignmentName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignment;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingRoleAssignments/{billingRoleAssignmentName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the billingRoleAssignmentsGetByBillingProfile operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsGetByBillingProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets a role assignment for the caller on a billing profile. The operation is supported for billing accounts with agreement type Microsoft Partner Agreement or Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {String} billingProfileName The ID that uniquely identifies a billing profile.
     * @param {String} billingRoleAssignmentName The ID that uniquely identifies a role assignment.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsGetByBillingProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignment}
     */
    billingRoleAssignmentsGetByBillingProfile(apiVersion, billingAccountName, billingProfileName, billingRoleAssignmentName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsGetByBillingProfile");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsGetByBillingProfile");
      }
      // verify the required parameter 'billingProfileName' is set
      if (billingProfileName === undefined || billingProfileName === null) {
        throw new Error("Missing the required parameter 'billingProfileName' when calling billingRoleAssignmentsGetByBillingProfile");
      }
      // verify the required parameter 'billingRoleAssignmentName' is set
      if (billingRoleAssignmentName === undefined || billingRoleAssignmentName === null) {
        throw new Error("Missing the required parameter 'billingRoleAssignmentName' when calling billingRoleAssignmentsGetByBillingProfile");
      }

      let pathParams = {
        'billingAccountName': billingAccountName,
        'billingProfileName': billingProfileName,
        'billingRoleAssignmentName': billingRoleAssignmentName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignment;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/billingRoleAssignments/{billingRoleAssignmentName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the billingRoleAssignmentsGetByInvoiceSection operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsGetByInvoiceSectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets a role assignment for the caller on an invoice section. The operation is supported for billing accounts with agreement type Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {String} billingProfileName The ID that uniquely identifies a billing profile.
     * @param {String} invoiceSectionName The ID that uniquely identifies an invoice section.
     * @param {String} billingRoleAssignmentName The ID that uniquely identifies a role assignment.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsGetByInvoiceSectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignment}
     */
    billingRoleAssignmentsGetByInvoiceSection(apiVersion, billingAccountName, billingProfileName, invoiceSectionName, billingRoleAssignmentName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsGetByInvoiceSection");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsGetByInvoiceSection");
      }
      // verify the required parameter 'billingProfileName' is set
      if (billingProfileName === undefined || billingProfileName === null) {
        throw new Error("Missing the required parameter 'billingProfileName' when calling billingRoleAssignmentsGetByInvoiceSection");
      }
      // verify the required parameter 'invoiceSectionName' is set
      if (invoiceSectionName === undefined || invoiceSectionName === null) {
        throw new Error("Missing the required parameter 'invoiceSectionName' when calling billingRoleAssignmentsGetByInvoiceSection");
      }
      // verify the required parameter 'billingRoleAssignmentName' is set
      if (billingRoleAssignmentName === undefined || billingRoleAssignmentName === null) {
        throw new Error("Missing the required parameter 'billingRoleAssignmentName' when calling billingRoleAssignmentsGetByInvoiceSection");
      }

      let pathParams = {
        'billingAccountName': billingAccountName,
        'billingProfileName': billingProfileName,
        'invoiceSectionName': invoiceSectionName,
        'billingRoleAssignmentName': billingRoleAssignmentName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignment;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}/billingRoleAssignments/{billingRoleAssignmentName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the billingRoleAssignmentsListByBillingAccount operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsListByBillingAccountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignmentListResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lists the role assignments for the caller on a billing account. The operation is supported for billing accounts with agreement type Microsoft Partner Agreement or Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsListByBillingAccountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignmentListResult}
     */
    billingRoleAssignmentsListByBillingAccount(apiVersion, billingAccountName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsListByBillingAccount");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsListByBillingAccount");
      }

      let pathParams = {
        'billingAccountName': billingAccountName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignmentListResult;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingRoleAssignments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the billingRoleAssignmentsListByBillingProfile operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsListByBillingProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignmentListResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lists the role assignments for the caller on a billing profile. The operation is supported for billing accounts with agreement type Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {String} billingProfileName The ID that uniquely identifies a billing profile.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsListByBillingProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignmentListResult}
     */
    billingRoleAssignmentsListByBillingProfile(apiVersion, billingAccountName, billingProfileName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsListByBillingProfile");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsListByBillingProfile");
      }
      // verify the required parameter 'billingProfileName' is set
      if (billingProfileName === undefined || billingProfileName === null) {
        throw new Error("Missing the required parameter 'billingProfileName' when calling billingRoleAssignmentsListByBillingProfile");
      }

      let pathParams = {
        'billingAccountName': billingAccountName,
        'billingProfileName': billingProfileName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignmentListResult;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/billingRoleAssignments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the billingRoleAssignmentsListByInvoiceSection operation.
     * @callback module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsListByInvoiceSectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BillingRoleAssignmentListResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lists the role assignments for the caller on an invoice section. The operation is supported for billing accounts with agreement type Microsoft Customer Agreement.
     * @param {String} apiVersion Version of the API to be used with the client request. The current version is 2018-03-01-preview.
     * @param {String} billingAccountName The ID that uniquely identifies a billing account.
     * @param {String} billingProfileName The ID that uniquely identifies a billing profile.
     * @param {String} invoiceSectionName The ID that uniquely identifies an invoice section.
     * @param {module:api/BillingRoleAssignmentsApi~billingRoleAssignmentsListByInvoiceSectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BillingRoleAssignmentListResult}
     */
    billingRoleAssignmentsListByInvoiceSection(apiVersion, billingAccountName, billingProfileName, invoiceSectionName, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling billingRoleAssignmentsListByInvoiceSection");
      }
      // verify the required parameter 'billingAccountName' is set
      if (billingAccountName === undefined || billingAccountName === null) {
        throw new Error("Missing the required parameter 'billingAccountName' when calling billingRoleAssignmentsListByInvoiceSection");
      }
      // verify the required parameter 'billingProfileName' is set
      if (billingProfileName === undefined || billingProfileName === null) {
        throw new Error("Missing the required parameter 'billingProfileName' when calling billingRoleAssignmentsListByInvoiceSection");
      }
      // verify the required parameter 'invoiceSectionName' is set
      if (invoiceSectionName === undefined || invoiceSectionName === null) {
        throw new Error("Missing the required parameter 'invoiceSectionName' when calling billingRoleAssignmentsListByInvoiceSection");
      }

      let pathParams = {
        'billingAccountName': billingAccountName,
        'billingProfileName': billingProfileName,
        'invoiceSectionName': invoiceSectionName
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BillingRoleAssignmentListResult;
      return this.apiClient.callApi(
        '/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}/billingRoleAssignments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
