transports:
  nativeProtocol:
    bindAddress: "0.0.0.0"
    portNumber: 35482
    secure: false
  pgProtocol:
    bindAddress: "0.0.0.0"
    portNumber: 35432
vdb:
  descriptorBundle: {{ DESCRIPTOR_BUNDLE }}

# Allows to specify an additional properties file path, useful when working in a Kubernetes environment with env vars
# specified in a ConfigMap rather than listing in the spec
propertiesFilePath: {{ PROPS_FILE }}