/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";

/**
 * The ChangeFeed model module.
 * @module model/ChangeFeed
 * @version 2023-01-01
 */
class ChangeFeed {
    /**
     * Constructs a new <code>ChangeFeed</code>.
     * The blob service properties for change feed events.
     * @alias module:model/ChangeFeed
     */
    constructor() { 
        
        ChangeFeed.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChangeFeed</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeFeed} obj Optional instance to populate.
     * @return {module:model/ChangeFeed} The populated <code>ChangeFeed</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeFeed();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('retentionInDays')) {
                obj['retentionInDays'] = ApiClient.convertToType(data['retentionInDays'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChangeFeed</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChangeFeed</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Indicates whether change feed event logging is enabled for the Blob service.
 * @member {Boolean} enabled
 */
ChangeFeed.prototype['enabled'] = undefined;

/**
 * Indicates the duration of changeFeed retention in days. Minimum value is 1 day and maximum value is 146000 days (400 years). A null value indicates an infinite retention of the change feed.
 * @member {Number} retentionInDays
 */
ChangeFeed.prototype['retentionInDays'] = undefined;






export default ChangeFeed;

