/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";

/**
 * The EncryptionScopeKeyVaultProperties model module.
 * @module model/EncryptionScopeKeyVaultProperties
 * @version 2023-01-01
 */
class EncryptionScopeKeyVaultProperties {
    /**
     * Constructs a new <code>EncryptionScopeKeyVaultProperties</code>.
     * The key vault properties for the encryption scope. This is a required field if encryption scope &#39;source&#39; attribute is set to &#39;Microsoft.KeyVault&#39;.
     * @alias module:model/EncryptionScopeKeyVaultProperties
     */
    constructor() { 
        
        EncryptionScopeKeyVaultProperties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EncryptionScopeKeyVaultProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EncryptionScopeKeyVaultProperties} obj Optional instance to populate.
     * @return {module:model/EncryptionScopeKeyVaultProperties} The populated <code>EncryptionScopeKeyVaultProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EncryptionScopeKeyVaultProperties();

            if (data.hasOwnProperty('keyUri')) {
                obj['keyUri'] = ApiClient.convertToType(data['keyUri'], 'String');
            }
            if (data.hasOwnProperty('currentVersionedKeyIdentifier')) {
                obj['currentVersionedKeyIdentifier'] = ApiClient.convertToType(data['currentVersionedKeyIdentifier'], 'String');
            }
            if (data.hasOwnProperty('lastKeyRotationTimestamp')) {
                obj['lastKeyRotationTimestamp'] = ApiClient.convertToType(data['lastKeyRotationTimestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EncryptionScopeKeyVaultProperties</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EncryptionScopeKeyVaultProperties</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['keyUri'] && !(typeof data['keyUri'] === 'string' || data['keyUri'] instanceof String)) {
            throw new Error("Expected the field `keyUri` to be a primitive type in the JSON string but got " + data['keyUri']);
        }
        // ensure the json data is a string
        if (data['currentVersionedKeyIdentifier'] && !(typeof data['currentVersionedKeyIdentifier'] === 'string' || data['currentVersionedKeyIdentifier'] instanceof String)) {
            throw new Error("Expected the field `currentVersionedKeyIdentifier` to be a primitive type in the JSON string but got " + data['currentVersionedKeyIdentifier']);
        }

        return true;
    }


}



/**
 * The object identifier for a key vault key object. When applied, the encryption scope will use the key referenced by the identifier to enable customer-managed key support on this encryption scope.
 * @member {String} keyUri
 */
EncryptionScopeKeyVaultProperties.prototype['keyUri'] = undefined;

/**
 * The object identifier of the current versioned Key Vault Key in use.
 * @member {String} currentVersionedKeyIdentifier
 */
EncryptionScopeKeyVaultProperties.prototype['currentVersionedKeyIdentifier'] = undefined;

/**
 * Timestamp of last rotation of the Key Vault Key.
 * @member {Date} lastKeyRotationTimestamp
 */
EncryptionScopeKeyVaultProperties.prototype['lastKeyRotationTimestamp'] = undefined;






export default EncryptionScopeKeyVaultProperties;

