/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
import ManagementPolicyDefinition from './ManagementPolicyDefinition';

/**
 * The ManagementPolicyRule model module.
 * @module model/ManagementPolicyRule
 * @version 2023-01-01
 */
class ManagementPolicyRule {
    /**
     * Constructs a new <code>ManagementPolicyRule</code>.
     * An object that wraps the Lifecycle rule. Each rule is uniquely defined by name.
     * @alias module:model/ManagementPolicyRule
     * @param name {String} A rule name can contain any combination of alpha numeric characters. Rule name is case-sensitive. It must be unique within a policy.
     * @param type {module:model/ManagementPolicyRule.TypeEnum} The valid value is Lifecycle
     * @param definition {module:model/ManagementPolicyDefinition} 
     */
    constructor(name, type, definition) { 
        
        ManagementPolicyRule.initialize(this, name, type, definition);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, type, definition) { 
        obj['name'] = name;
        obj['type'] = type;
        obj['definition'] = definition;
    }

    /**
     * Constructs a <code>ManagementPolicyRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ManagementPolicyRule} obj Optional instance to populate.
     * @return {module:model/ManagementPolicyRule} The populated <code>ManagementPolicyRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManagementPolicyRule();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('definition')) {
                obj['definition'] = ManagementPolicyDefinition.constructFromObject(data['definition']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ManagementPolicyRule</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ManagementPolicyRule</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ManagementPolicyRule.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // validate the optional field `definition`
        if (data['definition']) { // data not null
          ManagementPolicyDefinition.validateJSON(data['definition']);
        }

        return true;
    }


}

ManagementPolicyRule.RequiredProperties = ["name", "type", "definition"];

/**
 * Rule is enabled if set to true.
 * @member {Boolean} enabled
 */
ManagementPolicyRule.prototype['enabled'] = undefined;

/**
 * A rule name can contain any combination of alpha numeric characters. Rule name is case-sensitive. It must be unique within a policy.
 * @member {String} name
 */
ManagementPolicyRule.prototype['name'] = undefined;

/**
 * The valid value is Lifecycle
 * @member {module:model/ManagementPolicyRule.TypeEnum} type
 */
ManagementPolicyRule.prototype['type'] = undefined;

/**
 * @member {module:model/ManagementPolicyDefinition} definition
 */
ManagementPolicyRule.prototype['definition'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ManagementPolicyRule['TypeEnum'] = {

    /**
     * value: "Lifecycle"
     * @const
     */
    "Lifecycle": "Lifecycle"
};



export default ManagementPolicyRule;

