/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
/**
* Enum class PrivateEndpointServiceConnectionStatus.
* @enum {}
* @readonly
*/
export default class PrivateEndpointServiceConnectionStatus {
    
        /**
         * value: "Pending"
         * @const
         */
        "Pending" = "Pending";

    
        /**
         * value: "Approved"
         * @const
         */
        "Approved" = "Approved";

    
        /**
         * value: "Rejected"
         * @const
         */
        "Rejected" = "Rejected";

    

    /**
    * Returns a <code>PrivateEndpointServiceConnectionStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PrivateEndpointServiceConnectionStatus} The enum <code>PrivateEndpointServiceConnectionStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

