/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
/**
* Enum class PrivateEndpointConnectionProvisioningState.
* @enum {}
* @readonly
*/
export default class PrivateEndpointConnectionProvisioningState {
    
        /**
         * value: "Succeeded"
         * @const
         */
        "Succeeded" = "Succeeded";

    
        /**
         * value: "Creating"
         * @const
         */
        "Creating" = "Creating";

    
        /**
         * value: "Deleting"
         * @const
         */
        "Deleting" = "Deleting";

    
        /**
         * value: "Failed"
         * @const
         */
        "Failed" = "Failed";

    

    /**
    * Returns a <code>PrivateEndpointConnectionProvisioningState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PrivateEndpointConnectionProvisioningState} The enum <code>PrivateEndpointConnectionProvisioningState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

