/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
import StorageAccountMigrationProperties from './StorageAccountMigrationProperties';

/**
 * The StorageAccountMigration model module.
 * @module model/StorageAccountMigration
 * @version 2023-01-01
 */
class StorageAccountMigration {
    /**
     * Constructs a new <code>StorageAccountMigration</code>.
     * The parameters or status associated with an ongoing or enqueued storage account migration in order to update its current SKU or region.
     * @alias module:model/StorageAccountMigration
     * @param properties {module:model/StorageAccountMigrationProperties} 
     */
    constructor(properties) { 
        
        StorageAccountMigration.initialize(this, properties);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, properties) { 
        obj['properties'] = properties;
    }

    /**
     * Constructs a <code>StorageAccountMigration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StorageAccountMigration} obj Optional instance to populate.
     * @return {module:model/StorageAccountMigration} The populated <code>StorageAccountMigration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageAccountMigration();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = StorageAccountMigrationProperties.constructFromObject(data['properties']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageAccountMigration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageAccountMigration</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StorageAccountMigration.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // validate the optional field `properties`
        if (data['properties']) { // data not null
          StorageAccountMigrationProperties.validateJSON(data['properties']);
        }

        return true;
    }


}

StorageAccountMigration.RequiredProperties = ["properties"];

/**
 * Migration Resource Id
 * @member {String} id
 */
StorageAccountMigration.prototype['id'] = undefined;

/**
 * current value is 'default' for customer initiated migration
 * @member {String} name
 */
StorageAccountMigration.prototype['name'] = undefined;

/**
 * SrpAccountMigrationType in ARM contract which is 'accountMigrations'
 * @member {String} type
 */
StorageAccountMigration.prototype['type'] = undefined;

/**
 * @member {module:model/StorageAccountMigrationProperties} properties
 */
StorageAccountMigration.prototype['properties'] = undefined;






export default StorageAccountMigration;

