/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
import SkuName from './SkuName';

/**
 * The StorageAccountSkuConversionStatus model module.
 * @module model/StorageAccountSkuConversionStatus
 * @version 2023-01-01
 */
class StorageAccountSkuConversionStatus {
    /**
     * Constructs a new <code>StorageAccountSkuConversionStatus</code>.
     * This defines the sku conversion status object for asynchronous sku conversions.
     * @alias module:model/StorageAccountSkuConversionStatus
     */
    constructor() { 
        
        StorageAccountSkuConversionStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StorageAccountSkuConversionStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StorageAccountSkuConversionStatus} obj Optional instance to populate.
     * @return {module:model/StorageAccountSkuConversionStatus} The populated <code>StorageAccountSkuConversionStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageAccountSkuConversionStatus();

            if (data.hasOwnProperty('skuConversionStatus')) {
                obj['skuConversionStatus'] = ApiClient.convertToType(data['skuConversionStatus'], 'String');
            }
            if (data.hasOwnProperty('targetSkuName')) {
                obj['targetSkuName'] = SkuName.constructFromObject(data['targetSkuName']);
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'String');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageAccountSkuConversionStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageAccountSkuConversionStatus</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['skuConversionStatus'] && !(typeof data['skuConversionStatus'] === 'string' || data['skuConversionStatus'] instanceof String)) {
            throw new Error("Expected the field `skuConversionStatus` to be a primitive type in the JSON string but got " + data['skuConversionStatus']);
        }
        // ensure the json data is a string
        if (data['startTime'] && !(typeof data['startTime'] === 'string' || data['startTime'] instanceof String)) {
            throw new Error("Expected the field `startTime` to be a primitive type in the JSON string but got " + data['startTime']);
        }
        // ensure the json data is a string
        if (data['endTime'] && !(typeof data['endTime'] === 'string' || data['endTime'] instanceof String)) {
            throw new Error("Expected the field `endTime` to be a primitive type in the JSON string but got " + data['endTime']);
        }

        return true;
    }


}



/**
 * This property indicates the current sku conversion status.
 * @member {module:model/StorageAccountSkuConversionStatus.SkuConversionStatusEnum} skuConversionStatus
 */
StorageAccountSkuConversionStatus.prototype['skuConversionStatus'] = undefined;

/**
 * @member {module:model/SkuName} targetSkuName
 */
StorageAccountSkuConversionStatus.prototype['targetSkuName'] = undefined;

/**
 * This property represents the sku conversion start time.
 * @member {String} startTime
 */
StorageAccountSkuConversionStatus.prototype['startTime'] = undefined;

/**
 * This property represents the sku conversion end time.
 * @member {String} endTime
 */
StorageAccountSkuConversionStatus.prototype['endTime'] = undefined;





/**
 * Allowed values for the <code>skuConversionStatus</code> property.
 * @enum {String}
 * @readonly
 */
StorageAccountSkuConversionStatus['SkuConversionStatusEnum'] = {

    /**
     * value: "InProgress"
     * @const
     */
    "InProgress": "InProgress",

    /**
     * value: "Succeeded"
     * @const
     */
    "Succeeded": "Succeeded",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed"
};



export default StorageAccountSkuConversionStatus;

