/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";

/**
 * The TableAccessPolicy model module.
 * @module model/TableAccessPolicy
 * @version 2023-01-01
 */
class TableAccessPolicy {
    /**
     * Constructs a new <code>TableAccessPolicy</code>.
     * Table Access Policy Properties Object.
     * @alias module:model/TableAccessPolicy
     * @param permission {String} Required. List of abbreviated permissions. Supported permission values include 'r','a','u','d'
     */
    constructor(permission) { 
        
        TableAccessPolicy.initialize(this, permission);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, permission) { 
        obj['permission'] = permission;
    }

    /**
     * Constructs a <code>TableAccessPolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableAccessPolicy} obj Optional instance to populate.
     * @return {module:model/TableAccessPolicy} The populated <code>TableAccessPolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableAccessPolicy();

            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
            if (data.hasOwnProperty('expiryTime')) {
                obj['expiryTime'] = ApiClient.convertToType(data['expiryTime'], 'Date');
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableAccessPolicy</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableAccessPolicy</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TableAccessPolicy.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['permission'] && !(typeof data['permission'] === 'string' || data['permission'] instanceof String)) {
            throw new Error("Expected the field `permission` to be a primitive type in the JSON string but got " + data['permission']);
        }

        return true;
    }


}

TableAccessPolicy.RequiredProperties = ["permission"];

/**
 * Start time of the access policy
 * @member {Date} startTime
 */
TableAccessPolicy.prototype['startTime'] = undefined;

/**
 * Expiry time of the access policy
 * @member {Date} expiryTime
 */
TableAccessPolicy.prototype['expiryTime'] = undefined;

/**
 * Required. List of abbreviated permissions. Supported permission values include 'r','a','u','d'
 * @member {String} permission
 */
TableAccessPolicy.prototype['permission'] = undefined;






export default TableAccessPolicy;

