/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
import Usage from './Usage';

/**
 * The UsageListResult model module.
 * @module model/UsageListResult
 * @version 2023-01-01
 */
class UsageListResult {
    /**
     * Constructs a new <code>UsageListResult</code>.
     * The response from the List Usages operation.
     * @alias module:model/UsageListResult
     */
    constructor() { 
        
        UsageListResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsageListResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsageListResult} obj Optional instance to populate.
     * @return {module:model/UsageListResult} The populated <code>UsageListResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsageListResult();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], [Usage]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsageListResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsageListResult</code>.
     */
    static validateJSON(data) {
        if (data['value']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['value'])) {
                throw new Error("Expected the field `value` to be an array in the JSON data but got " + data['value']);
            }
            // validate the optional field `value` (array)
            for (const item of data['value']) {
                Usage.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Gets or sets the list of Storage Resource Usages.
 * @member {Array.<module:model/Usage>} value
 */
UsageListResult.prototype['value'] = undefined;






export default UsageListResult;

