/**
 * StorageManagementClient
 * The Azure Storage Management API.
 *
 * The version of the OpenAPI document: 2023-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../../BaseApiClient";
import DeletedAccount from '../model/DeletedAccount';
import DeletedAccountListResult from '../model/DeletedAccountListResult';
import ErrorResponse from '../model/ErrorResponse';

/**
* DeletedAccounts service.
* @module api/DeletedAccountsApi
* @version 2023-01-01
*/
export default class DeletedAccountsApi {

    /**
    * Constructs a new DeletedAccountsApi. 
    * @alias module:api/DeletedAccountsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deletedAccountsGet operation.
     * @callback module:api/DeletedAccountsApi~deletedAccountsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedAccount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get properties of specified deleted account resource.
     * @param {String} deletedAccountName Name of the deleted storage account.
     * @param {String} location The location of the deleted storage account.
     * @param {String} apiVersion The API version to use for this operation.
     * @param {String} subscriptionId The ID of the target subscription.
     * @param {module:api/DeletedAccountsApi~deletedAccountsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedAccount}
     */
    deletedAccountsGet(deletedAccountName, location, apiVersion, subscriptionId, callback) {
      let postBody = null;
      // verify the required parameter 'deletedAccountName' is set
      if (deletedAccountName === undefined || deletedAccountName === null) {
        throw new Error("Missing the required parameter 'deletedAccountName' when calling deletedAccountsGet");
      }
      // verify the required parameter 'location' is set
      if (location === undefined || location === null) {
        throw new Error("Missing the required parameter 'location' when calling deletedAccountsGet");
      }
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling deletedAccountsGet");
      }
      // verify the required parameter 'subscriptionId' is set
      if (subscriptionId === undefined || subscriptionId === null) {
        throw new Error("Missing the required parameter 'subscriptionId' when calling deletedAccountsGet");
      }

      let pathParams = {
        'deletedAccountName': deletedAccountName,
        'location': location,
        'subscriptionId': subscriptionId
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedAccount;
      return this.apiClient.callApi(
        '/subscriptions/{subscriptionId}/providers/Microsoft.Storage/locations/{location}/deletedAccounts/{deletedAccountName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deletedAccountsList operation.
     * @callback module:api/DeletedAccountsApi~deletedAccountsListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletedAccountListResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lists deleted accounts under the subscription.
     * @param {String} apiVersion The API version to use for this operation.
     * @param {String} subscriptionId The ID of the target subscription.
     * @param {module:api/DeletedAccountsApi~deletedAccountsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletedAccountListResult}
     */
    deletedAccountsList(apiVersion, subscriptionId, callback) {
      let postBody = null;
      // verify the required parameter 'apiVersion' is set
      if (apiVersion === undefined || apiVersion === null) {
        throw new Error("Missing the required parameter 'apiVersion' when calling deletedAccountsList");
      }
      // verify the required parameter 'subscriptionId' is set
      if (subscriptionId === undefined || subscriptionId === null) {
        throw new Error("Missing the required parameter 'subscriptionId' when calling deletedAccountsList");
      }

      let pathParams = {
        'subscriptionId': subscriptionId
      };
      let queryParams = {
        'api-version': apiVersion
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['azure_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeletedAccountListResult;
      return this.apiClient.callApi(
        '/subscriptions/{subscriptionId}/providers/Microsoft.Storage/deletedAccounts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
