/**
 * BillingManagementClient
 * Billing client provides access to billing resources for Azure subscriptions.
 *
 * The version of the OpenAPI document: 2020-05-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
import InvoiceSection from './InvoiceSection';

/**
 * The InvoiceSectionsOnExpand model module.
 * @module model/InvoiceSectionsOnExpand
 * @version 2020-05-01
 */
class InvoiceSectionsOnExpand {
    /**
     * Constructs a new <code>InvoiceSectionsOnExpand</code>.
     * The invoice sections associated to the billing profile. By default this is not populated, unless it&#39;s specified in $expand.
     * @alias module:model/InvoiceSectionsOnExpand
     */
    constructor() { 
        
        InvoiceSectionsOnExpand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InvoiceSectionsOnExpand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvoiceSectionsOnExpand} obj Optional instance to populate.
     * @return {module:model/InvoiceSectionsOnExpand} The populated <code>InvoiceSectionsOnExpand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvoiceSectionsOnExpand();

            if (data.hasOwnProperty('hasMoreResults')) {
                obj['hasMoreResults'] = ApiClient.convertToType(data['hasMoreResults'], 'Boolean');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], [InvoiceSection]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InvoiceSectionsOnExpand</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InvoiceSectionsOnExpand</code>.
     */
    static validateJSON(data) {
        if (data['value']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['value'])) {
                throw new Error("Expected the field `value` to be an array in the JSON data but got " + data['value']);
            }
            // validate the optional field `value` (array)
            for (const item of data['value']) {
                InvoiceSection.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Indicates whether there are more invoice sections than the ones listed in this collection. The collection lists a maximum of 50 invoice sections. To get all invoice sections, use the list invoice sections API.
 * @member {Boolean} hasMoreResults
 */
InvoiceSectionsOnExpand.prototype['hasMoreResults'] = undefined;

/**
 * The invoice sections associated to the billing profile.
 * @member {Array.<module:model/InvoiceSection>} value
 */
InvoiceSectionsOnExpand.prototype['value'] = undefined;






export default InvoiceSectionsOnExpand;

