/**
 * BillingManagementClient
 * Billing client provides access to billing resources for Azure subscriptions.
 *
 * The version of the OpenAPI document: 2020-05-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
/**
* Enum class SubscriptionTransferValidationErrorCode.
* @enum {}
* @readonly
*/
export default class SubscriptionTransferValidationErrorCode {
    
        /**
         * value: "BillingAccountInactive"
         * @const
         */
        "BillingAccountInactive" = "BillingAccountInactive";

    
        /**
         * value: "CrossBillingAccountNotAllowed"
         * @const
         */
        "CrossBillingAccountNotAllowed" = "CrossBillingAccountNotAllowed";

    
        /**
         * value: "DestinationBillingProfileInactive"
         * @const
         */
        "DestinationBillingProfileInactive" = "DestinationBillingProfileInactive";

    
        /**
         * value: "DestinationBillingProfileNotFound"
         * @const
         */
        "DestinationBillingProfileNotFound" = "DestinationBillingProfileNotFound";

    
        /**
         * value: "DestinationBillingProfilePastDue"
         * @const
         */
        "DestinationBillingProfilePastDue" = "DestinationBillingProfilePastDue";

    
        /**
         * value: "DestinationInvoiceSectionInactive"
         * @const
         */
        "DestinationInvoiceSectionInactive" = "DestinationInvoiceSectionInactive";

    
        /**
         * value: "DestinationInvoiceSectionNotFound"
         * @const
         */
        "DestinationInvoiceSectionNotFound" = "DestinationInvoiceSectionNotFound";

    
        /**
         * value: "InsufficientPermissionOnDestination"
         * @const
         */
        "InsufficientPermissionOnDestination" = "InsufficientPermissionOnDestination";

    
        /**
         * value: "InsufficientPermissionOnSource"
         * @const
         */
        "InsufficientPermissionOnSource" = "InsufficientPermissionOnSource";

    
        /**
         * value: "InvalidDestination"
         * @const
         */
        "InvalidDestination" = "InvalidDestination";

    
        /**
         * value: "InvalidSource"
         * @const
         */
        "InvalidSource" = "InvalidSource";

    
        /**
         * value: "MarketplaceNotEnabledOnDestination"
         * @const
         */
        "MarketplaceNotEnabledOnDestination" = "MarketplaceNotEnabledOnDestination";

    
        /**
         * value: "NotAvailableForDestinationMarket"
         * @const
         */
        "NotAvailableForDestinationMarket" = "NotAvailableForDestinationMarket";

    
        /**
         * value: "ProductInactive"
         * @const
         */
        "ProductInactive" = "ProductInactive";

    
        /**
         * value: "ProductNotFound"
         * @const
         */
        "ProductNotFound" = "ProductNotFound";

    
        /**
         * value: "ProductTypeNotSupported"
         * @const
         */
        "ProductTypeNotSupported" = "ProductTypeNotSupported";

    
        /**
         * value: "SourceBillingProfilePastDue"
         * @const
         */
        "SourceBillingProfilePastDue" = "SourceBillingProfilePastDue";

    
        /**
         * value: "SourceInvoiceSectionInactive"
         * @const
         */
        "SourceInvoiceSectionInactive" = "SourceInvoiceSectionInactive";

    
        /**
         * value: "SubscriptionNotActive"
         * @const
         */
        "SubscriptionNotActive" = "SubscriptionNotActive";

    
        /**
         * value: "SubscriptionTypeNotSupported"
         * @const
         */
        "SubscriptionTypeNotSupported" = "SubscriptionTypeNotSupported";

    

    /**
    * Returns a <code>SubscriptionTransferValidationErrorCode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/SubscriptionTransferValidationErrorCode} The enum <code>SubscriptionTransferValidationErrorCode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

