/**
 * BillingManagementClient
 * Billing client provides access to billing resources for Azure subscriptions.
 *
 * The version of the OpenAPI document: 2020-05-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../../BaseApiClient";
import ValidateProductTransferEligibilityError from './ValidateProductTransferEligibilityError';

/**
 * The ValidateProductTransferEligibilityResult model module.
 * @module model/ValidateProductTransferEligibilityResult
 * @version 2020-05-01
 */
class ValidateProductTransferEligibilityResult {
    /**
     * Constructs a new <code>ValidateProductTransferEligibilityResult</code>.
     * Result of the product transfer eligibility validation.
     * @alias module:model/ValidateProductTransferEligibilityResult
     */
    constructor() { 
        
        ValidateProductTransferEligibilityResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidateProductTransferEligibilityResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidateProductTransferEligibilityResult} obj Optional instance to populate.
     * @return {module:model/ValidateProductTransferEligibilityResult} The populated <code>ValidateProductTransferEligibilityResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidateProductTransferEligibilityResult();

            if (data.hasOwnProperty('isMoveEligible')) {
                obj['isMoveEligible'] = ApiClient.convertToType(data['isMoveEligible'], 'Boolean');
            }
            if (data.hasOwnProperty('errorDetails')) {
                obj['errorDetails'] = ValidateProductTransferEligibilityError.constructFromObject(data['errorDetails']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidateProductTransferEligibilityResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidateProductTransferEligibilityResult</code>.
     */
    static validateJSON(data) {
        // validate the optional field `errorDetails`
        if (data['errorDetails']) { // data not null
          ValidateProductTransferEligibilityError.validateJSON(data['errorDetails']);
        }

        return true;
    }


}



/**
 * Specifies whether the transfer is eligible or not.
 * @member {Boolean} isMoveEligible
 */
ValidateProductTransferEligibilityResult.prototype['isMoveEligible'] = undefined;

/**
 * @member {module:model/ValidateProductTransferEligibilityError} errorDetails
 */
ValidateProductTransferEligibilityResult.prototype['errorDetails'] = undefined;






export default ValidateProductTransferEligibilityResult;

