# Optional, in case default port is in use, or you want to restrict interfaces
transports:
  nativeProtocol:
    bindAddress: {{ NATIVE_PROTOCOL_BIND_ADDRESS }}
    portNumber: {{ NATIVE_PROTOCOL_PORT }}
  pgProtocol:
    bindAddress: "0.0.0.0"
    portNumber: 35432
vdb:
  # DESCRIPTOR_BUNDLE must be specified as an environment variable. You can also use a URI string
  descriptorBundle: {{ DESCRIPTOR_BUNDLE }}