{% set vdb = "k8s" %}
{% set tables = getTablesByTags(vdb=_context.vdb, schema="all", tags="kubernetes;deployment_container_vols") %}
---

type: sqlDirect
virtualDatabase: {{ vdb }}

neededFields:
  - namespace

# Templates support pipe command which is used to filter values, in this case filterValWhenVarFalse gets "UNION ALL"
# and decides whether to print it or not based on 'first' variable.
query: |
  {% set first = true %}
  {% for table in tables %}
    {{ "UNION ALL" | filterValWhenVarFalse(var="first", flip=true) }}
    SELECT * FROM {{ table }} WHERE metadata__namespace = '{{ namespace }}'
  {% endfor %}
    ORDER BY clusterName
