---
name: "DB"
version: "1"

dataSourceModels:
  - name: "tk_ds"
    dataSourceType: "SCRIPT_JS"
    config: "bundle:scripting/k8s-config.yaml"

translatorModels:
  - name: "js_translator"
    dataSourceType: "SCRIPT_JS"
    config: "bundle:translator/k8s-translator.yaml"

schemaModels:
  - name: "tk"
    type: "PHYSICAL"
    dataMappings:
      js_translator: "tk_ds"
    ddl: |
      CREATE FOREIGN TABLE MY_TOKEN
                (token__inmem string, token__decrypted string)
            OPTIONS(updatable false);