---
name: "DB"
version: "1"

dataSources:
  - name: "tk_ds"
    dataSourceType: "SCRIPT_JS"
    config: "bundle:scripting/js-config.yaml"
    translatorConfig: "bundle:translator/js-translator.yaml"
    schema:
      type: "PHYSICAL"
      ddl: |
        CREATE FOREIGN TABLE MY_TOKEN
                  (token__inmem string, token__decrypted string)
              OPTIONS(updatable false);
