supportsCompareCriteriaEquals: true
supportsInCriteria: true
supportsLikeCriteria: true
supportsOrCriteria: true
supportsRowLimit: true
supportsRowOffset: true
supportsNotCriteria: true
supportsOnlyLiteralComparison: true
supportsLikeCriteriaEscapeCharacter: true
useAnsiJoin: true

# This Azure API client does not support pagination, so the Engine handles limit and offset.
delegatePaginationToEngine: true