server:
  port: 8282
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: dbvirt-sample-hibernate
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.kubling.teiid.jdbc.TeiidDriver
    hikari:
      connection-timeout: 60000
      hikari:
        maximum-pool-size: 10
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    open-in-view: true
    packagesToScan:
      - 'com.kubling.*'
    show-sql: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        dialect: com.kubling.hibernate.dialect.KublingDialect
        id:
          new-generator-mappings: false
        use-new-id-generator-mappings: false
        format_sql: true
        hbm2ddl:
          auto: none

---
spring:
  config:
    activate:
      on-profile: unit-test
  datasource:
    url: jdbc:teiid:TestVDB@mm://localhost:35482
    username: sa
    password: sa