/**
 * AzureArcDataManagementClient
 * The AzureArcData management API provides a RESTful set of web APIs to manage Azure Data Services on Azure Arc Resources.
 *
 * The version of the OpenAPI document: 2023-01-15-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ExtendedLocationType.
* @enum {}
* @readonly
*/
export default class ExtendedLocationType {
    
        /**
         * value: "CustomLocation"
         * @const
         */
        "CustomLocation" = "CustomLocation";

    

    /**
    * Returns a <code>ExtendedLocationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ExtendedLocationType} The enum <code>ExtendedLocationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

