/**
 * AzureArcDataManagementClient
 * The AzureArcData management API provides a RESTful set of web APIs to manage Azure Data Services on Azure Arc Resources.
 *
 * The version of the OpenAPI document: 2023-01-15-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CommonSku from './CommonSku';

/**
 * The PostgresInstanceSku model module.
 * @module model/PostgresInstanceSku
 * @version 2023-01-15-preview
 */
class PostgresInstanceSku {
    /**
     * Constructs a new <code>PostgresInstanceSku</code>.
     * The resource model definition representing SKU for Azure Database for PostgreSQL - Azure Arc
     * @alias module:model/PostgresInstanceSku
     * @implements module:model/CommonSku
     * @param name {String} The name of the SKU.  It is typically a letter+number code
     */
    constructor(name) { 
        CommonSku.initialize(this, name);
        PostgresInstanceSku.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>PostgresInstanceSku</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostgresInstanceSku} obj Optional instance to populate.
     * @return {module:model/PostgresInstanceSku} The populated <code>PostgresInstanceSku</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostgresInstanceSku();
            CommonSku.constructFromObject(data, obj);

            if (data.hasOwnProperty('tier')) {
                obj['tier'] = ApiClient.convertToType(data['tier'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('dev')) {
                obj['dev'] = ApiClient.convertToType(data['dev'], 'Boolean');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'String');
            }
            if (data.hasOwnProperty('family')) {
                obj['family'] = ApiClient.convertToType(data['family'], 'String');
            }
            if (data.hasOwnProperty('capacity')) {
                obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostgresInstanceSku</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostgresInstanceSku</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostgresInstanceSku.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['tier'] && !(typeof data['tier'] === 'string' || data['tier'] instanceof String)) {
            throw new Error("Expected the field `tier` to be a primitive type in the JSON string but got " + data['tier']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['size'] && !(typeof data['size'] === 'string' || data['size'] instanceof String)) {
            throw new Error("Expected the field `size` to be a primitive type in the JSON string but got " + data['size']);
        }
        // ensure the json data is a string
        if (data['family'] && !(typeof data['family'] === 'string' || data['family'] instanceof String)) {
            throw new Error("Expected the field `family` to be a primitive type in the JSON string but got " + data['family']);
        }

        return true;
    }


}

PostgresInstanceSku.RequiredProperties = ["name"];

/**
 * This field is required to be implemented by the Resource Provider if the service has more than one tier.
 * @member {module:model/PostgresInstanceSku.TierEnum} tier
 * @default 'Hyperscale'
 */
PostgresInstanceSku.prototype['tier'] = 'Hyperscale';

/**
 * The name of the SKU.  It is typically a letter+number code
 * @member {String} name
 */
PostgresInstanceSku.prototype['name'] = undefined;

/**
 * Whether dev/test is enabled. When the dev field is set to true, the resource is used for dev/test purpose. 
 * @member {Boolean} dev
 * @default true
 */
PostgresInstanceSku.prototype['dev'] = true;

/**
 * The SKU size. When the name field is the combination of tier and some other value, this would be the standalone code. 
 * @member {String} size
 */
PostgresInstanceSku.prototype['size'] = undefined;

/**
 * If the service has different generations of hardware, for the same SKU, then that can be captured here.
 * @member {String} family
 */
PostgresInstanceSku.prototype['family'] = undefined;

/**
 * If the SKU supports scale out/in then the capacity integer should be included. If scale out/in is not possible for the resource this may be omitted.
 * @member {Number} capacity
 */
PostgresInstanceSku.prototype['capacity'] = undefined;


// Implement CommonSku interface:
/**
 * The name of the SKU.  It is typically a letter+number code
 * @member {String} name
 */
CommonSku.prototype['name'] = undefined;
/**
 * Whether dev/test is enabled. When the dev field is set to true, the resource is used for dev/test purpose. 
 * @member {Boolean} dev
 * @default true
 */
CommonSku.prototype['dev'] = true;
/**
 * The SKU size. When the name field is the combination of tier and some other value, this would be the standalone code. 
 * @member {String} size
 */
CommonSku.prototype['size'] = undefined;
/**
 * If the service has different generations of hardware, for the same SKU, then that can be captured here.
 * @member {String} family
 */
CommonSku.prototype['family'] = undefined;
/**
 * If the SKU supports scale out/in then the capacity integer should be included. If scale out/in is not possible for the resource this may be omitted.
 * @member {Number} capacity
 */
CommonSku.prototype['capacity'] = undefined;



/**
 * Allowed values for the <code>tier</code> property.
 * @enum {String}
 * @readonly
 */
PostgresInstanceSku['TierEnum'] = {

    /**
     * value: "Hyperscale"
     * @const
     */
    "Hyperscale": "Hyperscale"
};



export default PostgresInstanceSku;

