/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArchiveUpdateProperties from './ArchiveUpdateProperties';

/**
 * The ArchiveUpdateParameters model module.
 * @module model/ArchiveUpdateParameters
 * @version 2019-06-01-preview
 */
class ArchiveUpdateParameters {
    /**
     * Constructs a new <code>ArchiveUpdateParameters</code>.
     * The parameters for updating a archive.
     * @alias module:model/ArchiveUpdateParameters
     */
    constructor() { 
        
        ArchiveUpdateParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ArchiveUpdateParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArchiveUpdateParameters} obj Optional instance to populate.
     * @return {module:model/ArchiveUpdateParameters} The populated <code>ArchiveUpdateParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArchiveUpdateParameters();

            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ArchiveUpdateProperties.constructFromObject(data['properties']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ArchiveUpdateParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArchiveUpdateParameters</code>.
     */
    static validateJSON(data) {
        // validate the optional field `properties`
        if (data['properties']) { // data not null
          ArchiveUpdateProperties.validateJSON(data['properties']);
        }

        return true;
    }


}



/**
 * @member {module:model/ArchiveUpdateProperties} properties
 */
ArchiveUpdateParameters.prototype['properties'] = undefined;






export default ArchiveUpdateParameters;

