/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CredentialHealth from './CredentialHealth';

/**
 * The AuthCredential model module.
 * @module model/AuthCredential
 * @version 2019-06-01-preview
 */
class AuthCredential {
    /**
     * Constructs a new <code>AuthCredential</code>.
     * Authentication credential stored for an upstream.
     * @alias module:model/AuthCredential
     */
    constructor() { 
        
        AuthCredential.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthCredential</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthCredential} obj Optional instance to populate.
     * @return {module:model/AuthCredential} The populated <code>AuthCredential</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthCredential();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('usernameSecretIdentifier')) {
                obj['usernameSecretIdentifier'] = ApiClient.convertToType(data['usernameSecretIdentifier'], 'String');
            }
            if (data.hasOwnProperty('passwordSecretIdentifier')) {
                obj['passwordSecretIdentifier'] = ApiClient.convertToType(data['passwordSecretIdentifier'], 'String');
            }
            if (data.hasOwnProperty('credentialHealth')) {
                obj['credentialHealth'] = CredentialHealth.constructFromObject(data['credentialHealth']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthCredential</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthCredential</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['usernameSecretIdentifier'] && !(typeof data['usernameSecretIdentifier'] === 'string' || data['usernameSecretIdentifier'] instanceof String)) {
            throw new Error("Expected the field `usernameSecretIdentifier` to be a primitive type in the JSON string but got " + data['usernameSecretIdentifier']);
        }
        // ensure the json data is a string
        if (data['passwordSecretIdentifier'] && !(typeof data['passwordSecretIdentifier'] === 'string' || data['passwordSecretIdentifier'] instanceof String)) {
            throw new Error("Expected the field `passwordSecretIdentifier` to be a primitive type in the JSON string but got " + data['passwordSecretIdentifier']);
        }
        // validate the optional field `credentialHealth`
        if (data['credentialHealth']) { // data not null
          CredentialHealth.validateJSON(data['credentialHealth']);
        }

        return true;
    }


}



/**
 * The name of the credential.
 * @member {module:model/AuthCredential.NameEnum} name
 */
AuthCredential.prototype['name'] = undefined;

/**
 * KeyVault Secret URI for accessing the username.
 * @member {String} usernameSecretIdentifier
 */
AuthCredential.prototype['usernameSecretIdentifier'] = undefined;

/**
 * KeyVault Secret URI for accessing the password.
 * @member {String} passwordSecretIdentifier
 */
AuthCredential.prototype['passwordSecretIdentifier'] = undefined;

/**
 * @member {module:model/CredentialHealth} credentialHealth
 */
AuthCredential.prototype['credentialHealth'] = undefined;





/**
 * Allowed values for the <code>name</code> property.
 * @enum {String}
 * @readonly
 */
AuthCredential['NameEnum'] = {

    /**
     * value: "Credential1"
     * @const
     */
    "Credential1": "Credential1"
};



export default AuthCredential;

