/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Argument from './Argument';
import BaseImageDependency from './BaseImageDependency';
import TaskStepProperties from './TaskStepProperties';

/**
 * The DockerBuildStep model module.
 * @module model/DockerBuildStep
 * @version 2019-06-01-preview
 */
class DockerBuildStep {
    /**
     * Constructs a new <code>DockerBuildStep</code>.
     * The Docker build step.
     * @alias module:model/DockerBuildStep
     * @extends module:model/TaskStepProperties
     * @implements module:model/TaskStepProperties
     * @param type {module:model/DockerBuildStep.TypeEnum} The type of the step.
     */
    constructor(type) { 
        TaskStepProperties.initialize(this, type);
        DockerBuildStep.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['dockerFilePath'] = dockerFilePath;
    }

    /**
     * Constructs a <code>DockerBuildStep</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DockerBuildStep} obj Optional instance to populate.
     * @return {module:model/DockerBuildStep} The populated <code>DockerBuildStep</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DockerBuildStep();
            TaskStepProperties.constructFromObject(data, obj);
            TaskStepProperties.constructFromObject(data, obj);

            if (data.hasOwnProperty('imageNames')) {
                obj['imageNames'] = ApiClient.convertToType(data['imageNames'], ['String']);
            }
            if (data.hasOwnProperty('isPushEnabled')) {
                obj['isPushEnabled'] = ApiClient.convertToType(data['isPushEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('noCache')) {
                obj['noCache'] = ApiClient.convertToType(data['noCache'], 'Boolean');
            }
            if (data.hasOwnProperty('dockerFilePath')) {
                obj['dockerFilePath'] = ApiClient.convertToType(data['dockerFilePath'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('arguments')) {
                obj['arguments'] = ApiClient.convertToType(data['arguments'], [Argument]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DockerBuildStep</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DockerBuildStep</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DockerBuildStep.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['imageNames'])) {
            throw new Error("Expected the field `imageNames` to be an array in the JSON data but got " + data['imageNames']);
        }
        // ensure the json data is a string
        if (data['dockerFilePath'] && !(typeof data['dockerFilePath'] === 'string' || data['dockerFilePath'] instanceof String)) {
            throw new Error("Expected the field `dockerFilePath` to be a primitive type in the JSON string but got " + data['dockerFilePath']);
        }
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }
        if (data['arguments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['arguments'])) {
                throw new Error("Expected the field `arguments` to be an array in the JSON data but got " + data['arguments']);
            }
            // validate the optional field `arguments` (array)
            for (const item of data['arguments']) {
                Argument.validateJSON(item);
            };
        }

        return true;
    }


}

DockerBuildStep.RequiredProperties = ["dockerFilePath", "type"];

/**
 * The fully qualified image names including the repository and tag.
 * @member {Array.<String>} imageNames
 */
DockerBuildStep.prototype['imageNames'] = undefined;

/**
 * The value of this property indicates whether the image built should be pushed to the registry or not.
 * @member {Boolean} isPushEnabled
 * @default true
 */
DockerBuildStep.prototype['isPushEnabled'] = true;

/**
 * The value of this property indicates whether the image cache is enabled or not.
 * @member {Boolean} noCache
 * @default false
 */
DockerBuildStep.prototype['noCache'] = false;

/**
 * The Docker file path relative to the source context.
 * @member {String} dockerFilePath
 */
DockerBuildStep.prototype['dockerFilePath'] = undefined;

/**
 * The name of the target build stage for the docker build.
 * @member {String} target
 */
DockerBuildStep.prototype['target'] = undefined;

/**
 * The collection of override arguments to be used when executing this build step.
 * @member {Array.<module:model/Argument>} arguments
 */
DockerBuildStep.prototype['arguments'] = undefined;


// Implement TaskStepProperties interface:
/**
 * The type of the step.
 * @member {module:model/TaskStepProperties.TypeEnum} type
 */
TaskStepProperties.prototype['type'] = undefined;
/**
 * List of base image dependencies for a step.
 * @member {Array.<module:model/BaseImageDependency>} baseImageDependencies
 */
TaskStepProperties.prototype['baseImageDependencies'] = undefined;
/**
 * The URL(absolute or relative) of the source context for the task step.
 * @member {String} contextPath
 */
TaskStepProperties.prototype['contextPath'] = undefined;
/**
 * The token (git PAT or SAS token of storage account blob) associated with the context for a step.
 * @member {String} contextAccessToken
 */
TaskStepProperties.prototype['contextAccessToken'] = undefined;




export default DockerBuildStep;

