/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IPRule model module.
 * @module model/IPRule
 * @version 2019-06-01-preview
 */
class IPRule {
    /**
     * Constructs a new <code>IPRule</code>.
     * IP rule with specific IP or IP range in CIDR format.
     * @alias module:model/IPRule
     * @param value {String} Specifies the IP or IP range in CIDR format. Only IPV4 address is allowed.
     */
    constructor(value) { 
        
        IPRule.initialize(this, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value) { 
        obj['value'] = value;
    }

    /**
     * Constructs a <code>IPRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IPRule} obj Optional instance to populate.
     * @return {module:model/IPRule} The populated <code>IPRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IPRule();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IPRule</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IPRule</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IPRule.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

IPRule.RequiredProperties = ["value"];

/**
 * The action of IP ACL rule.
 * @member {module:model/IPRule.ActionEnum} action
 * @default 'Allow'
 */
IPRule.prototype['action'] = 'Allow';

/**
 * Specifies the IP or IP range in CIDR format. Only IPV4 address is allowed.
 * @member {String} value
 */
IPRule.prototype['value'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
IPRule['ActionEnum'] = {

    /**
     * value: "Allow"
     * @const
     */
    "Allow": "Allow"
};



export default IPRule;

