/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RegistryUsage from './RegistryUsage';

/**
 * The RegistryUsageListResult model module.
 * @module model/RegistryUsageListResult
 * @version 2019-06-01-preview
 */
class RegistryUsageListResult {
    /**
     * Constructs a new <code>RegistryUsageListResult</code>.
     * The result of a request to get container registry quota usages.
     * @alias module:model/RegistryUsageListResult
     */
    constructor() { 
        
        RegistryUsageListResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegistryUsageListResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegistryUsageListResult} obj Optional instance to populate.
     * @return {module:model/RegistryUsageListResult} The populated <code>RegistryUsageListResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegistryUsageListResult();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], [RegistryUsage]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegistryUsageListResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegistryUsageListResult</code>.
     */
    static validateJSON(data) {
        if (data['value']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['value'])) {
                throw new Error("Expected the field `value` to be an array in the JSON data but got " + data['value']);
            }
            // validate the optional field `value` (array)
            for (const item of data['value']) {
                RegistryUsage.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The list of container registry quota usages.
 * @member {Array.<module:model/RegistryUsage>} value
 */
RegistryUsageListResult.prototype['value'] = undefined;






export default RegistryUsageListResult;

