/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegistryUsage model module.
 * @module model/RegistryUsage
 * @version 2019-06-01-preview
 */
class RegistryUsage {
    /**
     * Constructs a new <code>RegistryUsage</code>.
     * The quota usage for a container registry.
     * @alias module:model/RegistryUsage
     */
    constructor() { 
        
        RegistryUsage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegistryUsage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegistryUsage} obj Optional instance to populate.
     * @return {module:model/RegistryUsage} The populated <code>RegistryUsage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegistryUsage();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('currentValue')) {
                obj['currentValue'] = ApiClient.convertToType(data['currentValue'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegistryUsage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegistryUsage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['unit'] && !(typeof data['unit'] === 'string' || data['unit'] instanceof String)) {
            throw new Error("Expected the field `unit` to be a primitive type in the JSON string but got " + data['unit']);
        }

        return true;
    }


}



/**
 * The name of the usage.
 * @member {String} name
 */
RegistryUsage.prototype['name'] = undefined;

/**
 * The limit of the usage.
 * @member {Number} limit
 */
RegistryUsage.prototype['limit'] = undefined;

/**
 * The current value of the usage.
 * @member {Number} currentValue
 */
RegistryUsage.prototype['currentValue'] = undefined;

/**
 * The unit of measurement.
 * @member {module:model/RegistryUsage.UnitEnum} unit
 */
RegistryUsage.prototype['unit'] = undefined;





/**
 * Allowed values for the <code>unit</code> property.
 * @enum {String}
 * @readonly
 */
RegistryUsage['UnitEnum'] = {

    /**
     * value: "Count"
     * @const
     */
    "Count": "Count",

    /**
     * value: "Bytes"
     * @const
     */
    "Bytes": "Bytes"
};



export default RegistryUsage;

