/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RunGetLogResult model module.
 * @module model/RunGetLogResult
 * @version 2019-06-01-preview
 */
class RunGetLogResult {
    /**
     * Constructs a new <code>RunGetLogResult</code>.
     * The result of get log link operation.
     * @alias module:model/RunGetLogResult
     */
    constructor() { 
        
        RunGetLogResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RunGetLogResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RunGetLogResult} obj Optional instance to populate.
     * @return {module:model/RunGetLogResult} The populated <code>RunGetLogResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunGetLogResult();

            if (data.hasOwnProperty('logLink')) {
                obj['logLink'] = ApiClient.convertToType(data['logLink'], 'String');
            }
            if (data.hasOwnProperty('logArtifactLink')) {
                obj['logArtifactLink'] = ApiClient.convertToType(data['logArtifactLink'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RunGetLogResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RunGetLogResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['logLink'] && !(typeof data['logLink'] === 'string' || data['logLink'] instanceof String)) {
            throw new Error("Expected the field `logLink` to be a primitive type in the JSON string but got " + data['logLink']);
        }
        // ensure the json data is a string
        if (data['logArtifactLink'] && !(typeof data['logArtifactLink'] === 'string' || data['logArtifactLink'] instanceof String)) {
            throw new Error("Expected the field `logArtifactLink` to be a primitive type in the JSON string but got " + data['logArtifactLink']);
        }

        return true;
    }


}



/**
 * The link to logs for a run on a azure container registry.
 * @member {String} logLink
 */
RunGetLogResult.prototype['logLink'] = undefined;

/**
 * The link to logs in registry for a run on a azure container registry.
 * @member {String} logArtifactLink
 */
RunGetLogResult.prototype['logArtifactLink'] = undefined;






export default RunGetLogResult;

