/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SyncProperties model module.
 * @module model/SyncProperties
 * @version 2019-06-01-preview
 */
class SyncProperties {
    /**
     * Constructs a new <code>SyncProperties</code>.
     * The sync properties of the connected registry with its parent.
     * @alias module:model/SyncProperties
     * @param tokenId {String} The resource ID of the ACR token used to authenticate the connected registry to its parent during sync.
     * @param messageTtl {String} The period of time for which a message is available to sync before it is expired. Specify the duration using the format P[n]Y[n]M[n]DT[n]H[n]M[n]S as per ISO8601.
     */
    constructor(tokenId, messageTtl) { 
        
        SyncProperties.initialize(this, tokenId, messageTtl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tokenId, messageTtl) { 
        obj['tokenId'] = tokenId;
        obj['messageTtl'] = messageTtl;
    }

    /**
     * Constructs a <code>SyncProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SyncProperties} obj Optional instance to populate.
     * @return {module:model/SyncProperties} The populated <code>SyncProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SyncProperties();

            if (data.hasOwnProperty('tokenId')) {
                obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiClient.convertToType(data['schedule'], 'String');
            }
            if (data.hasOwnProperty('syncWindow')) {
                obj['syncWindow'] = ApiClient.convertToType(data['syncWindow'], 'String');
            }
            if (data.hasOwnProperty('messageTtl')) {
                obj['messageTtl'] = ApiClient.convertToType(data['messageTtl'], 'String');
            }
            if (data.hasOwnProperty('lastSyncTime')) {
                obj['lastSyncTime'] = ApiClient.convertToType(data['lastSyncTime'], 'Date');
            }
            if (data.hasOwnProperty('gatewayEndpoint')) {
                obj['gatewayEndpoint'] = ApiClient.convertToType(data['gatewayEndpoint'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SyncProperties</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SyncProperties</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SyncProperties.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['tokenId'] && !(typeof data['tokenId'] === 'string' || data['tokenId'] instanceof String)) {
            throw new Error("Expected the field `tokenId` to be a primitive type in the JSON string but got " + data['tokenId']);
        }
        // ensure the json data is a string
        if (data['schedule'] && !(typeof data['schedule'] === 'string' || data['schedule'] instanceof String)) {
            throw new Error("Expected the field `schedule` to be a primitive type in the JSON string but got " + data['schedule']);
        }
        // ensure the json data is a string
        if (data['syncWindow'] && !(typeof data['syncWindow'] === 'string' || data['syncWindow'] instanceof String)) {
            throw new Error("Expected the field `syncWindow` to be a primitive type in the JSON string but got " + data['syncWindow']);
        }
        // ensure the json data is a string
        if (data['messageTtl'] && !(typeof data['messageTtl'] === 'string' || data['messageTtl'] instanceof String)) {
            throw new Error("Expected the field `messageTtl` to be a primitive type in the JSON string but got " + data['messageTtl']);
        }
        // ensure the json data is a string
        if (data['gatewayEndpoint'] && !(typeof data['gatewayEndpoint'] === 'string' || data['gatewayEndpoint'] instanceof String)) {
            throw new Error("Expected the field `gatewayEndpoint` to be a primitive type in the JSON string but got " + data['gatewayEndpoint']);
        }

        return true;
    }


}

SyncProperties.RequiredProperties = ["tokenId", "messageTtl"];

/**
 * The resource ID of the ACR token used to authenticate the connected registry to its parent during sync.
 * @member {String} tokenId
 */
SyncProperties.prototype['tokenId'] = undefined;

/**
 * The cron expression indicating the schedule that the connected registry will sync with its parent.
 * @member {String} schedule
 */
SyncProperties.prototype['schedule'] = undefined;

/**
 * The time window during which sync is enabled for each schedule occurrence. Specify the duration using the format P[n]Y[n]M[n]DT[n]H[n]M[n]S as per ISO8601.
 * @member {String} syncWindow
 */
SyncProperties.prototype['syncWindow'] = undefined;

/**
 * The period of time for which a message is available to sync before it is expired. Specify the duration using the format P[n]Y[n]M[n]DT[n]H[n]M[n]S as per ISO8601.
 * @member {String} messageTtl
 */
SyncProperties.prototype['messageTtl'] = undefined;

/**
 * The last time a sync occurred between the connected registry and its parent.
 * @member {Date} lastSyncTime
 */
SyncProperties.prototype['lastSyncTime'] = undefined;

/**
 * The gateway endpoint used by the connected registry to communicate with its parent.
 * @member {String} gatewayEndpoint
 */
SyncProperties.prototype['gatewayEndpoint'] = undefined;






export default SyncProperties;

