/**
 * ContainerRegistryManagementClient
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019-06-01-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TlsCertificateProperties from './TlsCertificateProperties';

/**
 * The TlsProperties model module.
 * @module model/TlsProperties
 * @version 2019-06-01-preview
 */
class TlsProperties {
    /**
     * Constructs a new <code>TlsProperties</code>.
     * The TLS properties of the connected registry login server.
     * @alias module:model/TlsProperties
     */
    constructor() { 
        
        TlsProperties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TlsProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TlsProperties} obj Optional instance to populate.
     * @return {module:model/TlsProperties} The populated <code>TlsProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TlsProperties();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('certificate')) {
                obj['certificate'] = TlsCertificateProperties.constructFromObject(data['certificate']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TlsProperties</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TlsProperties</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `certificate`
        if (data['certificate']) { // data not null
          TlsCertificateProperties.validateJSON(data['certificate']);
        }

        return true;
    }


}



/**
 * Indicates whether HTTPS is enabled for the login server.
 * @member {module:model/TlsProperties.StatusEnum} status
 */
TlsProperties.prototype['status'] = undefined;

/**
 * @member {module:model/TlsCertificateProperties} certificate
 */
TlsProperties.prototype['certificate'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
TlsProperties['StatusEnum'] = {

    /**
     * value: "Enabled"
     * @const
     */
    "Enabled": "Enabled",

    /**
     * value: "Disabled"
     * @const
     */
    "Disabled": "Disabled"
};



export default TlsProperties;

