{% set vdb = "k8s" %}
{% set tables = getTablesByTags(vdb=_context.vdb, schema="all", tags=_context.clusterName + ";kubernetes;deployment_container_vols") %}
---
needed:
  fields:
    - clusterName
    - namespace
    - deploymentName
    - containerName
    - volName
    - volMountPath
    - volReadOnly

before:
  - name: "Deployment Container exists"
    virtualDatabase: {{ vdb }}
    # We don't expect more than one matching table here so we use 'first' filter...
    entity: "{{ tables | first }}"
    filters:
      - field: "metadata__namespace"
        value: {{ namespace }}
        operation: "EQUAL"
      - field: "metadata__name"
        value: {{ deploymentName }}
        operation: "EQUAL"
    assertThat: "exists"
    message: "Deployment {{ deploymentName }} does not exist in namespace {{ namespace }}."

# ********* OPERATIONS *********
operations:

  - name: "vol_insert"
    type: "insert"
    virtualDatabase: {{ vdb }}
    entity: "{{ tables | first }}"
    valueAssignments:
      - field: "metadata__name"
        value: {{ deploymentName }}
      - field: "metadata__namespace"
        value: {{ namespace }}
      - field: "containerName"
        value: {{ containerName }}
      - field: "mountPath"
        value: {{ volMountPath }}
      - field: "name"
        value: {{ volName }}
      - field: "readOnly"
        value: {{ volReadOnly }}