transports:
  nativeProtocol:
    bindAddress: {{ NATIVE_PROTOCOL_BIND_ADDRESS }}
    portNumber: {{ NATIVE_PROTOCOL_PORT }}
    secure: false
  pgProtocol:
    bindAddress: "0.0.0.0"
    portNumber: 35432
    secure: false
vdb:
  descriptorBundle: {{ DESCRIPTOR_BUNDLE }}

propertiesFilePath: {{ PROPS_FILE }}